// Generated by CoffeeScript 1.7.1
(function() {
  var convert;

  convert = function(token) {
    var i, letter, out, _i, _len, _ref;
    out = 0;
    _ref = token.split("");
    for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
      letter = _ref[i];
      out += letter.charCodeAt() * ((token.length / 8) / (i + 1)) * 0.8;
    }
    return out;
  };

  module.exports = convert;

}).call(this);
